ARG OPENSEARCH_DASHBOARDS_VERSION=2.18.0
FROM opensearchproject/opensearch-dashboards:${OPENSEARCH_DASHBOARDS_VERSION}
RUN /usr/share/opensearch-dashboards/bin/opensearch-dashboards-plugin remove securityDashboards